### ISSUE TITLE
HMScriptClient verliert Verbindung zur CCU2

### ISSUE THREAD

**Issue by arrlee** [mdzio/ccu-historian#103]
Hallo,

mein ccu-historian ist über OpenVPN mit der CCU2 verbunden. Nachts beobachte ich diverse VPN-Re-Connects, wahrscheinlich, weil der DSL-Provider die Verbindung kappt und neu aufbaut. Die Exceptions sind jeweils einem OpenVPN-Verbindungsaufbau zuzordnen. Nach einigen Exceptions stellt der historian die Arbeit für CuxD-Devices ein und fängt sich auch nicht mehr. Alle anderen Geräteklassen funktionieren problemlos weiter. Nur ein Neustart bringt das Monitoring für die CuxD-Geräte wieder zurück.

Danke & Grüsse,
André
```
2018-05-01 02:16:42|SEVERE |Exception: connect timed out
2018-05-01 02:16:42|SEVERE |Detail: java.net.SocketTimeoutException: connect timed out
        at mdz.hc.itf.hm.HmScriptClient.execute(HmScriptClient.groovy:352)
        at mdz.hc.itf.hm.HmScriptClient.getSystemVariableValues(HmScriptClient.groovy:104)
        at mdz.hc.itf.hm.HmSysVarInterface$_readVariables_closure3.doCall(HmSysVarInterface.groovy:118)
        at mdz.hc.itf.hm.HmSysVarInterface$_readVariables_closure3.call(HmSysVarInterface.groovy)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.hc.itf.hm.HmSysVarInterface.readVariables(HmSysVarInterface.groovy:116)
2018-05-01 03:09:33|SEVERE |Exception: connect timed out
2018-05-01 03:09:33|SEVERE |Detail: java.net.SocketTimeoutException: connect timed out
        at mdz.hc.itf.hm.HmScriptClient.execute(HmScriptClient.groovy:352)
        at mdz.hc.itf.hm.HmScriptClient.getSystemVariableValues(HmScriptClient.groovy:104)
        at mdz.hc.itf.hm.HmSysVarInterface$_readVariables_closure3.doCall(HmSysVarInterface.groovy:118)
        at mdz.hc.itf.hm.HmSysVarInterface$_readVariables_closure3.call(HmSysVarInterface.groovy)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.hc.itf.hm.HmSysVarInterface.readVariables(HmSysVarInterface.groovy:116)
2018-05-01 03:10:13|SEVERE |Exception: connect timed out
2018-05-01 03:10:13|SEVERE |Detail: java.net.SocketTimeoutException: connect timed out
        at mdz.hc.itf.hm.HmScriptClient.execute(HmScriptClient.groovy:352)
        at mdz.hc.itf.hm.HmScriptClient.getSystemVariableValues(HmScriptClient.groovy:104)
        at mdz.hc.itf.hm.HmSysVarInterface$_readVariables_closure3.doCall(HmSysVarInterface.groovy:118)
        at mdz.hc.itf.hm.HmSysVarInterface$_readVariables_closure3.call(HmSysVarInterface.groovy)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.hc.itf.hm.HmSysVarInterface.readVariables(HmSysVarInterface.groovy:116)
2018-05-01 03:10:53|SEVERE |Exception: connect timed out
2018-05-01 03:10:53|SEVERE |Detail: java.net.SocketTimeoutException: connect timed out
        at mdz.hc.itf.hm.HmScriptClient.execute(HmScriptClient.groovy:352)
        at mdz.hc.itf.hm.HmScriptClient.getSystemVariableValues(HmScriptClient.groovy:104)
        at mdz.hc.itf.hm.HmSysVarInterface$_readVariables_closure3.doCall(HmSysVarInterface.groovy:118)
        at mdz.hc.itf.hm.HmSysVarInterface$_readVariables_closure3.call(HmSysVarInterface.groovy)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.hc.itf.hm.HmSysVarInterface.readVariables(HmSysVarInterface.groovy:116)

```

**Comment by mdzio** [comment]
Welche Komponente (CCU-Historian, CCU oder CUxD) musste neu gestartet werden, damit CUxD-Geräte wieder aufgezeichnet werden?

Zur weiteren Fehleranalyse ist eine detaillierte Log-Datei über einen Verbindungsabbruch hinweg hilfreich (s.a. Handbuch Abschnitt 8.1).

**Comment by mdzio** [comment]
Fehlende Rückmeldung
