### ISSUE TITLE
Fehlermeldung Backup / Konvertierung

### ISSUE THREAD

**Issue by martz170** [mdzio/ccu-historian#141]
Ein Backup für die Konvertierung schlägt mit folgender Fehlermeldung fehl:

( DB wurde vorher von der CCU kopiert )

C:\ccu-historian-1.2.0-bin>java -jar ccu-historian.jar -config ccu-historian.config -createscript backup.sql
2018-12-08 14:06:51|INFO   |CCU-Historian V1.2.0
2018-12-08 14:06:51|INFO   |(C)MDZ (info@ccu-historian.de)
2018-12-08 14:06:51|INFO   |Starting base services
2018-12-08 14:06:52|INFO   |Starting dump of database
2018-12-08 14:06:53|SEVERE |Exception: Allgemeiner Fehler: "java.lang.IllegalArgumentException: timeNanos out of range 86400258000000"
General error: "java.lang.IllegalArgumentException: timeNanos out of range 86400258000000"; SQL statement:
SCRIPT  DROP TO 'backup.sql'  [50000-196]
2018-12-08 14:06:53|SEVERE |Detail: org.h2.jdbc.JdbcSQLException: Allgemeiner Fehler: "java.lang.IllegalArgumentException: timeNanos out of range 86400258000000"
General error: "java.lang.IllegalArgumentException: timeNanos out of range 86400258000000"; SQL statement:
SCRIPT  DROP TO 'backup.sql'  [50000-196]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:168)
        at org.h2.message.DbException.convert(DbException.java:295)
        at org.h2.command.Command.executeQuery(Command.java:215)
        at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:186)
        at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
        at org.h2.tools.Script.process(Script.java:139)
        at org.h2.tools.Script.process(Script.java:119)
        at org.h2.tools.Script.runTool(Script.java:100)
        at org.h2.tools.Script.main(Script.java:45)
        at mdz.ccuhistorian.Database.dump(Database.groovy:467)
        at mdz.ccuhistorian.OfflineMaintenanceSystem$_closure1$_closure2.doCall(OfflineMaintenanceSystem.groovy:41)
        at mdz.ccuhistorian.OfflineMaintenanceSystem$_closure1$_closure2.call(OfflineMaintenanceSystem.groovy)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.ccuhistorian.OfflineMaintenanceSystem$_closure1.doCall(OfflineMaintenanceSystem.groovy:41)
        at mdz.ccuhistorian.OfflineMaintenanceSystem$_closure1.call(OfflineMaintenanceSystem.groovy)
Caused by: java.lang.IllegalArgumentException: timeNanos out of range 86400258000000
        at org.h2.value.ValueTimestamp.<init>(ValueTimestamp.java:54)
        at org.h2.value.ValueTimestamp.fromDateValueAndNanos(ValueTimestamp.java:68)
        at org.h2.value.ValueTimestamp.fromMillisNanos(ValueTimestamp.java:95)
        at org.h2.store.Data.readValue(Data.java:780)
        at org.h2.index.PageDataLeaf.readRow(PageDataLeaf.java:623)
        at org.h2.index.PageDataLeaf.getRowAt(PageDataLeaf.java:333)
        at org.h2.index.PageDataCursor.nextRow(PageDataCursor.java:101)
        at org.h2.index.PageDataCursor.next(PageDataCursor.java:67)
        at org.h2.command.dml.ScriptCommand.generateInsertValues(ScriptCommand.java:409)
        at org.h2.command.dml.ScriptCommand.query(ScriptCommand.java:300)
        at org.h2.command.CommandContainer.query(CommandContainer.java:113)
        at org.h2.command.Command.executeQuery(Command.java:201)
        ... 14 more

C:\ccu-historian-1.2.0-bin>

**Comment by mdzio** [comment]
Das Backup muss mit der *V1.1.0* erstellt werden!

Die Datenbank muss mit der *V1.1.0* über die Kommandozeilenoption *-createscript* exportiert werden. Danach die Datenbankdateien im *data* Verzeichnis löschen. Die Datenbank dann mit der *V1.2.0* und der Option *-runscript* wieder herstellen. Sie wird dann automatisch im neuen Format angelegt. Dieser Schritt muss nur einmalig durchgeführt werden.
