### ISSUE TITLE
Error message on startup: ClassFormatError: Unknown constant tag 0

### ISSUE THREAD

**Issue by iuliusmaximilian** [mdzio/ccu-historian#149]
When I start cci-historian on my RaspPi3 with CCU3 by sudo java -jar ccu-historian.jar I get an error:

```
2019-01-15 16:05:19|INFO   |CCU-Historian V2.0.0-beta.5
2019-01-15 16:05:19|INFO   |(C)MDZ (info@ccu-historian.de)
2019-01-15 16:05:20|INFO   |Starting base services
2019-01-15 16:05:20|INFO   |Connecting to database
2019-01-15 16:05:22|INFO   |Starting database web server
2019-01-15 16:05:23|INFO   |Setting up device 1
2019-01-15 16:05:23|INFO   |Creating HM script client for http://10.0.1.10:8181/tclrega.exe
2019-01-15 16:05:23|INFO   |Setting up plug-in 1
2019-01-15 16:05:23|INFO   |Setting up plug-in 2
2019-01-15 16:05:23|INFO   |Configured following interfaces: BidCos-RF, HmIP-RF, SysVar, CUxD, BidCos-Wired
2019-01-15 16:05:23|INFO   |Starting interfaces
2019-01-15 16:05:23|INFO   |Starting BIN-RPC server on port 2099
2019-01-15 16:05:23|INFO   |Starting XML-RPC server on port 2098
2019-01-15 16:05:23|INFO   |Connecting to 10.0.1.10:8701
2019-01-15 16:05:23|INFO   |Starting historian
2019-01-15 16:05:24|INFO   |Starting web server
2019-01-15 16:05:24|WARNING|FAILED o.e.j.w.WebAppContext{/,file:/home/pi/ccu-historian/webapp/}: java.lang.ClassFormatError: Unknown constant tag 0 in class file com/sun/org/apache/xerces/internal/xni/parser/XMLPullParserConfiguration
2019-01-15 16:05:24|WARNING|Error starting handlers
java.lang.ClassFormatError: Unknown constant tag 0 in class file com/sun/org/apache/xerces/internal/xni/parser/XMLPullParserConfiguration
	at com.sun.org.apache.xerces.internal.parsers.SAXParser.<init>(SAXParser.java:111)
	at com.sun.org.apache.xerces.internal.parsers.SAXParser.<init>(SAXParser.java:96)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.<init>(SAXParserImpl.java:406)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.<init>(SAXParserImpl.java:135)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl.newSAXParser(SAXParserFactoryImpl.java:79)
	at org.eclipse.jetty.xml.XmlParser.setValidating(XmlParser.java:92)
	at org.eclipse.jetty.xml.XmlParser.<init>(XmlParser.java:73)
	at org.eclipse.jetty.webapp.WebDescriptor.newParser(WebDescriptor.java:64)
	at org.eclipse.jetty.webapp.WebDescriptor.ensureParser(WebDescriptor.java:55)
	at org.eclipse.jetty.webapp.Descriptor.parse(Descriptor.java:54)
	at org.eclipse.jetty.webapp.WebDescriptor.parse(WebDescriptor.java:142)
	at org.eclipse.jetty.webapp.MetaData.setDefaults(MetaData.java:142)
	at org.eclipse.jetty.webapp.WebXmlConfiguration.preConfigure(WebXmlConfiguration.java:46)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:465)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:495)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
	at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:93)
	at org.eclipse.jetty.server.Server.doStart(Server.java:243)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:55)
	at mdz.ccuhistorian.webapp.WebServer.<init>(WebServer.groovy:66)
	at mdz.ccuhistorian.HistorianSystem.<init>(HistorianSystem.groovy:41)
	at mdz.ccuhistorian.Main.start(Main.groovy:102)
	at mdz.ccuhistorian.Main.access$0(Main.groovy)
	at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy:79)
	at mdz.ccuhistorian.Main$_run_closure4.call(Main.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Main.run(Main.groovy:79)
	at mdz.ccuhistorian.Main.main(Main.groovy:47)
2019-01-15 16:05:24|INFO   |Web server port: 8080
2019-01-15 16:05:44|WARNING|Communication error
2019-01-15 16:05:44|WARNING|Exception: Unknown instance
2019-01-15 16:05:44|WARNING|Detail: uk.co.wilson.net.xmlrpc.XMLRPCFailException: Unknown instance
	at uk.co.wilson.net.xmlrpc.XMLRPCMessageProcessor.endElement(XMLRPCMessageProcessor.java:627)
	at uk.co.wilson.xml.MinML.parse(MinML.java:312)
	at uk.co.wilson.net.xmlrpc.XMLRPCMessageProcessor.parseMessage(XMLRPCMessageProcessor.java:443)
	at mdz.hc.itf.hm.HmXmlRpcClient.getParamsetDescription(HmXmlRpcClient.groovy:54)
	at mdz.hc.itf.hm.HmXmlRpcInterface$_updateDeviceProperties_closure3.doCall(HmXmlRpcInterface.groovy:182)
	at mdz.hc.itf.hm.HmXmlRpcInterface.updateDeviceProperties(HmXmlRpcInterface.groovy:156)
	at mdz.hc.itf.hm.HmXmlRpcInterface.updateProperties(HmXmlRpcInterface.groovy:230)
	at mdz.hc.itf.Manager$_updateProperties_closure4.doCall(Manager.groovy:121)
	at mdz.hc.itf.Manager.updateProperties(Manager.groovy:118)
	at mdz.ccuhistorian.Historian.update(Historian.groovy:154)
	at mdz.ccuhistorian.Historian.access$2(Historian.groovy)
	at mdz.ccuhistorian.Historian$_updateDataPointMeta_closure3$_closure12.doCall(Historian.groovy:114)
	at mdz.ccuhistorian.Historian$_updateDataPointMeta_closure3$_closure12.call(Historian.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Historian$_updateDataPointMeta_closure3.doCall(Historian.groovy:110)
	at mdz.ccuhistorian.Historian.updateDataPointMeta(Historian.groovy:109)
	at mdz.ccuhistorian.Historian.access$0(Historian.groovy)
	at mdz.ccuhistorian.Historian$_run_closure2.doCall(Historian.groovy:103)
	at mdz.ccuhistorian.Historian$_run_closure2.call(Historian.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Historian.run(Historian.groovy:102)
```

**Comment by mdzio** [comment]
Please install the final version 2.0.0 and repeat the test.

**Comment by iuliusmaximilian** [comment]
Solved it!

**Comment by mdzio** [comment]
Hast Du den CCU-Historian als Add-On auf der CCU3 installiert?
Unter welcher Firmware-Version der CCU3 wird der CCU-Historian gestartet?

**Comment by iuliusmaximilian** [comment]
CCU-Historian auf meinem RaspPI 3

**Comment by mdzio** [comment]
Der Fehler tritt anscheinend nur beim Start des Web-Servers auf. Bitte mal die Ausgabe von `java -version` zur Verfügung stellen.

**Comment by iuliusmaximilian** [comment]
```
pi@raspberrypi:~ $ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)
pi@raspberrypi:~ $ 
```

**Comment by iuliusmaximilian** [comment]
For now, a Java Update solved it.

https://raspberrypi.stackexchange.com/questions/45976/how-do-i-update-java-8-in-raspbian

pi@raspberrypi:~ $ java -version
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) Client VM (build 25.201-b09, mixed mode)
