### ISSUE TITLE
Fehler: The database has been closed [90098-199]

### ISSUE THREAD

**Issue by iuliusmaximilian** [mdzio/ccu-historian#196]
Ich habe meinen Rasp3 sowie CCU3 jeweils auf alle latest aktualisiert und bekomme seitdem folgende Fehlermeldung wenn ich mir im Browser Datenpunkte anschauen möchte (v2.2.2):

```
org.h2.jdbc.JdbcSQLNonTransientConnectionException: The database has been closed [90098-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.engine.Session.getTransaction(Session.java:1709)
	at org.h2.engine.Session.startStatementWithinTransaction(Session.java:1729)
	at org.h2.command.Command.executeQuery(Command.java:196)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:85)
	at mdz.ccuhistorian.Database.getDataPoints(Database.groovy:223)
	at mdz.ccuhistorian.ExtendedStorage.getDataPoints(ExtendedStorage.groovy:44)
	at index$_run_closure2$_closure4$_closure8$_closure22.doCall(index.gy:128)
	at index$_run_closure2$_closure4$_closure8$_closure22.doCall(index.gy)
	at index$_run_closure2$_closure4$_closure8.doCall(index.gy:127)
	at index$_run_closure2$_closure4$_closure8.doCall(index.gy)
	at index$_run_closure2$_closure4.doCall(index.gy:104)
	at index$_run_closure2$_closure4.doCall(index.gy)
	at index$_run_closure2.doCall(index.gy:32)
	at index$_run_closure2.doCall(index.gy)
	at mdz.ccuhistorian.webapp.PageRenderer$_runSafe_closure2.doCall(PageRenderer.groovy:53)
	at mdz.ccuhistorian.webapp.PageRenderer$_runSafe_closure2.doCall(PageRenderer.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.webapp.WebUtilities.catchToLog(WebUtilities.groovy:81)
	at mdz.ccuhistorian.webapp.PageRenderer.runSafe(PageRenderer.groovy:51)
	at mdz.ccuhistorian.webapp.PageRenderer.writeContent(PageRenderer.groovy:279)
	at mdz.ccuhistorian.webapp.PageRenderer$_writeBody_closure6$_closure11.doCall(PageRenderer.groovy:137)
	at mdz.ccuhistorian.webapp.PageRenderer$_writeBody_closure6$_closure11.doCall(PageRenderer.groovy)
	at mdz.ccuhistorian.webapp.PageRenderer$_writeBody_closure6.doCall(PageRenderer.groovy:132)
	at mdz.ccuhistorian.webapp.PageRenderer$_writeBody_closure6.doCall(PageRenderer.groovy)
	at mdz.ccuhistorian.webapp.PageRenderer.writeBody(PageRenderer.groovy:131)
	at mdz.ccuhistorian.webapp.PageRenderer$_writeDocument_closure4.doCall(PageRenderer.groovy:103)
	at mdz.ccuhistorian.webapp.PageRenderer$_writeDocument_closure4.doCall(PageRenderer.groovy)
	at mdz.ccuhistorian.webapp.PageRenderer.writeDocument(PageRenderer.groovy:101)
	at mdz.ccuhistorian.webapp.PageRenderer$_render_closure1.doCall(PageRenderer.groovy:24)
	at mdz.ccuhistorian.webapp.PageRenderer$_render_closure1.doCall(PageRenderer.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.webapp.WebUtilities.catchToLog(WebUtilities.groovy:81)
	at mdz.ccuhistorian.webapp.PageRenderer.render(PageRenderer.groovy:21)
	at index.run(index.gy:230)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1351)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:186)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:158)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1322)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:516)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:929)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:864)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
	at org.eclipse.jetty.server.Server.handle(Server.java:352)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1051)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:508)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:451)
Caused by: java.lang.IllegalStateException: Writing to nio:/media/pi/Elements/ccu-historian/data/history.mv.db failed; length 1216513 at 4294873088 [1.4.199/2]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.DataUtils.writeFully(DataUtils.java:443)
	at org.h2.mvstore.FileStore.writeFully(FileStore.java:113)
	at org.h2.mvstore.MVStore.write(MVStore.java:935)
	at org.h2.mvstore.MVStore.storeNow(MVStore.java:1332)
	at org.h2.mvstore.MVStore.store(MVStore.java:1190)
	at org.h2.mvstore.MVStore.tryCommit(MVStore.java:1135)
	at org.h2.mvstore.MVStore.beforeWrite(MVStore.java:2436)
	at org.h2.mvstore.MVMap.beforeWrite(MVMap.java:897)
	at org.h2.mvstore.MVMap.operate(MVMap.java:1649)
	at org.h2.mvstore.MVMap.replace(MVMap.java:500)
	at org.h2.mvstore.MVMap.rewritePage(MVMap.java:648)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:601)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:615)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:615)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:615)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:590)
	at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2164)
	at org.h2.mvstore.MVStore.compact(MVStore.java:2041)
	at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2776)
	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3123)
Caused by: java.io.IOException: File too large
	at org.h2.store.fs.FileNio.write(FilePathNio.java:79)
	at org.h2.mvstore.DataUtils.writeFully(DataUtils.java:439)
	... 19 more](url)Fehler: The database has been closed [90098-199]

Details
org.h2.jdbc.JdbcSQLNonTransientConnectionException: The database has been closed [90098-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.engine.Session.getTransaction(Session.java:1709)
	at org.h2.engine.Session.startStatementWithinTransaction(Session.java:1729)
	at org.h2.command.Command.executeQuery(Command.java:196)
	at org.h2.jdbc.JdbcStatement.executeQuery(JdbcStatement.java:85)
	at mdz.ccuhistorian.Database.getDataPoints(Database.groovy:223)
	at mdz.ccuhistorian.ExtendedStorage.getDataPoints(ExtendedStorage.groovy:44)
	at index$_run_closure2$_closure4$_closure8$_closure22.doCall(index.gy:128)
	at index$_run_closure2$_closure4$_closure8$_closure22.doCall(index.gy)
	at index$_run_closure2$_closure4$_closure8.doCall(index.gy:127)
	at index$_run_closure2$_closure4$_closure8.doCall(index.gy)
	at index$_run_closure2$_closure4.doCall(index.gy:104)
	at index$_run_closure2$_closure4.doCall(index.gy)
	at index$_run_closure2.doCall(index.gy:32)
	at index$_run_closure2.doCall(index.gy)
	at mdz.ccuhistorian.webapp.PageRenderer$_runSafe_closure2.doCall(PageRenderer.groovy:53)
	at mdz.ccuhistorian.webapp.PageRenderer$_runSafe_closure2.doCall(PageRenderer.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.webapp.WebUtilities.catchToLog(WebUtilities.groovy:81)
	at mdz.ccuhistorian.webapp.PageRenderer.runSafe(PageRenderer.groovy:51)
	at mdz.ccuhistorian.webapp.PageRenderer.writeContent(PageRenderer.groovy:279)
	at mdz.ccuhistorian.webapp.PageRenderer$_writeBody_closure6$_closure11.doCall(PageRenderer.groovy:137)
	at mdz.ccuhistorian.webapp.PageRenderer$_writeBody_closure6$_closure11.doCall(PageRenderer.groovy)
	at mdz.ccuhistorian.webapp.PageRenderer$_writeBody_closure6.doCall(PageRenderer.groovy:132)
	at mdz.ccuhistorian.webapp.PageRenderer$_writeBody_closure6.doCall(PageRenderer.groovy)
	at mdz.ccuhistorian.webapp.PageRenderer.writeBody(PageRenderer.groovy:131)
	at mdz.ccuhistorian.webapp.PageRenderer$_writeDocument_closure4.doCall(PageRenderer.groovy:103)
	at mdz.ccuhistorian.webapp.PageRenderer$_writeDocument_closure4.doCall(PageRenderer.groovy)
	at mdz.ccuhistorian.webapp.PageRenderer.writeDocument(PageRenderer.groovy:101)
	at mdz.ccuhistorian.webapp.PageRenderer$_render_closure1.doCall(PageRenderer.groovy:24)
	at mdz.ccuhistorian.webapp.PageRenderer$_render_closure1.doCall(PageRenderer.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.webapp.WebUtilities.catchToLog(WebUtilities.groovy:81)
	at mdz.ccuhistorian.webapp.PageRenderer.render(PageRenderer.groovy:21)
	at index.run(index.gy:230)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1351)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:186)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:158)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1322)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:473)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:516)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:929)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:864)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
	at org.eclipse.jetty.server.Server.handle(Server.java:352)
	at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
	at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1051)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
	at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:508)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:451)
Caused by: java.lang.IllegalStateException: Writing to nio:/media/pi/Elements/ccu-historian/data/history.mv.db failed; length 1216513 at 4294873088 [1.4.199/2]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.DataUtils.writeFully(DataUtils.java:443)
	at org.h2.mvstore.FileStore.writeFully(FileStore.java:113)
	at org.h2.mvstore.MVStore.write(MVStore.java:935)
	at org.h2.mvstore.MVStore.storeNow(MVStore.java:1332)
	at org.h2.mvstore.MVStore.store(MVStore.java:1190)
	at org.h2.mvstore.MVStore.tryCommit(MVStore.java:1135)
	at org.h2.mvstore.MVStore.beforeWrite(MVStore.java:2436)
	at org.h2.mvstore.MVMap.beforeWrite(MVMap.java:897)
	at org.h2.mvstore.MVMap.operate(MVMap.java:1649)
	at org.h2.mvstore.MVMap.replace(MVMap.java:500)
	at org.h2.mvstore.MVMap.rewritePage(MVMap.java:648)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:601)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:615)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:615)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:615)
	at org.h2.mvstore.MVMap.rewrite(MVMap.java:590)
	at org.h2.mvstore.MVStore.compactRewrite(MVStore.java:2164)
	at org.h2.mvstore.MVStore.compact(MVStore.java:2041)
	at org.h2.mvstore.MVStore.writeInBackground(MVStore.java:2776)
	at org.h2.mvstore.MVStore$BackgroundWriterThread.run(MVStore.java:3123)
Caused by: java.io.IOException: File too large
	at org.h2.store.fs.FileNio.write(FilePathNio.java:79)
	at org.h2.mvstore.DataUtils.writeFully(DataUtils.java:439)
	... 19 more
```

**Comment by mdzio** [comment]
Wird der CCU-Historian als Add-On auf der CCU betrieben?
Wird ein USB-Stick verwendet? Mit welchem Dateisystem ist der Stick formartiert?
Wie groß ist denn die Datenbank?

**Comment by mdzio** [comment]
Im [Forum wurde berichtet](https://homematic-forum.de/forum/viewtopic.php?f=38&t=54635&p=545383#p545304), dass der Fehler nach einem Update auf die Version 2.3.1 verschwunden ist. Kann das bestätigt werden?
