### ISSUE TITLE
Update auf Synology von 2.2.0 -> 2.3.0 .... Datenbank defekt ?!

### ISSUE THREAD

**Issue by roe1974** [mdzio/ccu-historian#201]
Habe heute von 2.2.0 auf 2.3.0 upgedatet ..... nun startet Historian nicht mehr ... folgende im log:

2019-11-19 14:31:20|INFO   |Starting base services
2019-11-19 14:31:20|INFO   |Connecting to database
2019-11-19 14:31:20|SEVERE |Exception: Datei fehlerhaft beim Lesen des Datensatzes: null. Mögliche Lösung: Recovery Werkzeug verwenden
File corrupted while reading record: null. Possible solution: use the recovery tool [90030-199]
2019-11-19 14:31:20|SEVERE |Detail: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Datei fehlerhaft beim Lesen des Datensatzes: null. Mögliche Lösung: Recovery Werkzeug verwenden
File corrupted while reading record: null. Possible solution: use the recovery tool [90030-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:205)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at mdz.ccuhistorian.Database.<init>(Database.groovy:71)
	at mdz.ccuhistorian.DatabaseSystem.<init>(DatabaseSystem.groovy:33)
	at mdz.ccuhistorian.HistorianSystem.<init>(HistorianSystem.groovy:34)
	at mdz.ccuhistorian.Main.start(Main.groovy:100)
	at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy:77)
	at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Main.run(Main.groovy:77)
	at mdz.ccuhistorian.Main.main(Main.groovy:45)
Caused by: java.lang.IllegalStateException: File corrupted in chunk 6791987, expected page length 4..4096, got 285346804 [1.4.199/6]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1055)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
	at org.h2.mvstore.Page.get(Page.java:221)
	at org.h2.mvstore.MVMap.get(MVMap.java:402)
	at org.h2.mvstore.MVMap.get(MVMap.java:389)
	at org.h2.mvstore.MVStore.getChunk(MVStore.java:1088)
	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1025)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
	at org.h2.mvstore.Cursor.traverseDown(Cursor.java:165)
	at org.h2.mvstore.Cursor.<init>(Cursor.java:31)
	at org.h2.mvstore.Cursor.<init>(Cursor.java:27)
	at org.h2.mvstore.MVMap.cursor(MVMap.java:660)
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:792)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:401)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	... 25 more

Ich mache tägliches Backup der DB .... wie gehe ich am besten vor ?

lg Richard

**Comment by roe1974** [comment]
Kann es sein dass im Synology Paket noch die h2db version 1.4.199 enthalten ist (sehe ich zumindest so auf meiner Synology .... Die soll ja lauit issue probleme machen ?!?!?
lg RIchard

**Comment by roe1974** [comment]
Konnte jetzt mit einem Backup die DB wieder zum laufen bringen......
2 Fragen:
Die DB ist jetzt nurmehr 700MB statt 1,5GB ... normal ?
Eine history.trace.db habe ich auch nicht mehr .. auch normal ?

lg RIchard

**Comment by mdzio** [comment]
Bei einem Backup und anschließendem Restore wird automatisch die Datenbank gepackt. Das gleiche macht auch die Kommandozeilenoption `-compact`. Die Abfragen werden dann auch schneller.
In der history.trace.db werden Datenbankfehler aufgezeichnet. Diese Datei wird außer zur Fehlersuche nicht benötigt. Jetzt wäre der Inhalt hilfreich.
Wie hast Du denn das Update eingespielt? Hast Du auch den CCU-Historian vorher gestoppt?

**Comment by roe1974** [comment]
wie immer ... historian gestoppt ... update im paketzentrum installiert ... historian gestartet ...
nur ist da diesmal was schief gegangen :(
brauchst du die trace.db ? 
... und sollte im synology paket nicht auch die h2db 1.4.200 enthalten sein ? ... ich sehe die 1.4.199

lg richard

**Comment by mdzio** [comment]
Ja, die Datei `trace.db` wäre interessant.
Im CCU-Historian V2.3.0 ist noch nicht die V1.4.200 der Datenbank enthalten. Die V2.3.1 wollte ich aber heute noch veröffentlichen.

**Comment by roe1974** [comment]
ok ... wohin soll ich die trace.db schicken ?
lg richard

**Comment by mdzio** [comment]
Die E-Mail-Adresse findest Du auf [dieser Seite](https://ccu-historian.de/index.php?n=CCU-Historian.ImpressumAmpHaftungsausschluss). Die V2.3.1 wird es auch für Synology geben.

**Comment by mdzio** [comment]
Ich schließe mal diesen Eintrag, bis eventuell ein ähnlicher Fehler mit der V2.3.1 auftritt.
