### ISSUE TITLE
Geister Datenpunkt sorgt für Absturz

### ISSUE THREAD

**Issue by derkopp** [mdzio/ccu-historian#205]
Hallo, ich habe ein sehr seltsames Verhalten. Historian wirft regelmäßig eine Exception, weil ein Datenpunkt nicht existiert.

Ausgangssituation:
Komplett neu aufgesetzter Historian als Addon auf Raspberrymatic. Datenbank gelöscht.

Log:
`2019-12-23 23:09:03|SEVERE |Exception: Unknown data point: 243
2019-12-23 23:09:03|SEVERE |Detail: java.lang.IllegalArgumentException: Unknown data point: 243
        at mdz.ccuhistorian.webapp.WebUtilities.getDataPoint(WebUtilities.groovy:108)
        at mdz.ccuhistorian.webapp.TrendParametersV2$_closure3.doCall(TrendParametersV2.groovy:65)
        at mdz.ccuhistorian.webapp.TrendParametersV2.<init>(TrendParametersV2.groovy:63)
        at mdz.ccuhistorian.webapp.TrendParameters.from(TrendParameters.groovy:53)
        at mdz.ccuhistorian.webapp.TrendParameters$from.call(Unknown Source)
        at trend$_run_closure1.doCall(trend.gy:216)
        at trend$_run_closure1.doCall(trend.gy)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.ccuhistorian.webapp.WebUtilities.catchToLog(WebUtilities.groovy:81)
        at trend.run(trend.gy:206)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:534)        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1351)
        at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:186)
        at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:158)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1322)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:473)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:516)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:929)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:403)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:184)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:864)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:114)
        at org.eclipse.jetty.server.Server.handle(Server.java:352)
        at org.eclipse.jetty.server.HttpConnection.handleRequest(HttpConnection.java:596)
        at org.eclipse.jetty.server.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:1051)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:590)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:212)
        at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:426)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:508)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.access$000(SelectChannelEndPoint.java:34)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:40)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:451)
`
In die Datenbank kann ich nicht schauen. Nutze ich das Webinterface und gebe den korrekten Pfad an (/media/usb0/ccu-historian/historian) erscheint immer die Meldung „ Database "/media/usb1/ccu-historian/historian" not found“ - aus irgendeinem Grund wird aus der „0“ eine „1“.

**Comment by mdzio** [comment]
Mit welchen Schritten kannst Du denn den Fehler produzieren?

**Comment by mdzio** [comment]
Bitte wieder melden, falls der Fehler wieder auftritt.

**Comment by tgw-de** [comment]
Hi,
besteht noch Interesse? Ich habe gerade genau diesen Fehler an einem absolut neu aufgesetzten System mit überschaubaren Komponenten. In die Datenbank komme ich auch und derzeit ist es so, dass durch die fehlerhaften Datenpunkte die restlichen nicht mehr eingelesen werden. Mir fehlen also sehr viele Geräte. 
Es ist reproduzierbar mit der V 2.6 und der aktuellen 2.7 beta 3.

**Comment by tgw-de** [comment]
Mir ist zusätzlich aufgefallen, dass nicht alle Datenpunkte, die im Historian sind, auch in den Highchrts vorhanden sind. Falls das interessant ist. Wird das noch irgendwo anders gespeichert?

**Comment by mdzio** [comment]
Bitte mal eine Log-Datei erstellen ([s.a. Handbuch](https://github.com/mdzio/ccu-historian/wiki#erstellung-eines-fehlerprotokolls)).
Bei welcher Aktion tritt der Fehler aus?

**Comment by mdzio** [comment]
> Ich schicke Dir jetzt ein Log mit

Die Log-Datei wurde nicht durch GitHub weitergeleitet. Bitte an info Klammeraffe ccu-historian Punkt de schicken oder im Forum per private Nachricht.

>  Aufgefallen ist mir, dass die Alarmvariable "out of range" ist.

Das ist nur eine Warnmeldung.
