### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Reading from nio:

### ISSUE THREAD

**Issue by iuliusmaximilian** [mdzio/ccu-historian#208]
Seit einigen Tagen bekomme ich folgende Exception

```
2020-02-16 02:58:34|INFO   |CCU-Historian V2.3.0
2020-02-16 02:58:34|INFO   |(C)MDZ (info@ccu-historian.de)
2020-02-16 02:58:37|INFO   |Starting base services
2020-02-16 02:58:38|INFO   |Connecting to database
2020-02-16 02:58:39|SEVERE |Exception: IO Exception: null [90028-199]
2020-02-16 02:58:39|SEVERE |Detail: org.h2.jdbc.JdbcSQLNonTransientException: IO Exception: null [90028-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:197)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at mdz.ccuhistorian.Database.<init>(Database.groovy:71)
	at mdz.ccuhistorian.DatabaseSystem.<init>(DatabaseSystem.groovy:33)
	at mdz.ccuhistorian.HistorianSystem.<init>(HistorianSystem.groovy:34)
	at mdz.ccuhistorian.Main.start(Main.groovy:100)
	at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy:77)
	at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Main.run(Main.groovy:77)
	at mdz.ccuhistorian.Main.main(Main.groovy:45)
Caused by: java.lang.IllegalStateException: Reading from nio:/media/pi/Elements/ccu-historian/data/history.mv.db failed; file length 454946816 read length 192 at 455984520 [1.4.199/1]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883) 
```

**Comment by mdzio** [comment]
Anscheinend ist die Datenbankdatei defekt. In der Regel kann die Dateibankdatei mit dem [Recovery-Werkzeug](https://github.com/mdzio/ccu-historian/wiki/Tipps-&-Tricks#wiederherstellung-einer-defekten-datenbank) wieder hergestellt werden.
