### ISSUE TITLE
2.4.0-beta 2 db issue

### ISSUE THREAD

**Issue by oriziena** [mdzio/ccu-historian#209]
hi,
nach installation der beta erscheint folgender fehler im ccu-historian logfile.

`2020-03-10 08:34:02|INFO   |Connecting to database
2020-03-10 08:34:03|SEVERE |Error updating data point storage
2020-03-10 08:34:03|SEVERE |Exception: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-199]
2020-03-10 08:34:03|SEVERE |Detail: org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-199]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:617)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.mvstore.db.MVTableEngine$Store.convertIllegalStateException(MVTableEngine.java:205)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:173)
	at org.h2.mvstore.db.MVTableEngine.init(MVTableEngine.java:95)
	at org.h2.engine.Database.getPageStore(Database.java:2739)
	at org.h2.engine.Database.open(Database.java:769)
	at org.h2.engine.Database.openDatabase(Database.java:319)
	at org.h2.engine.Database.<init>(Database.java:313)
	at org.h2.engine.Engine.openSession(Engine.java:69)
	at org.h2.engine.Engine.openSession(Engine.java:201)
	at org.h2.engine.Engine.createSessionAndValidate(Engine.java:178)
	at org.h2.engine.Engine.createSession(Engine.java:161)
	at org.h2.engine.Engine.createSession(Engine.java:31)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:336)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:169)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:148)
	at org.h2.Driver.connect(Driver.java:69)
	at mdz.ccuhistorian.Database.connect(Database.groovy:78)
	at mdz.ccuhistorian.Database.getDataPoint(Database.groovy:260)
	at mdz.ccuhistorian.ExtendedStorage.getDataPoint(ExtendedStorage.groovy:59)
	at mdz.ccuhistorian.eventprocessing.DataPointStorageUpdater.consume(DataPointStorageUpdater.groovy:43)
	at mdz.ccuhistorian.eventprocessing.DataPointStorageUpdater.consume(DataPointStorageUpdater.groovy)
	at mdz.eventprocessing.BasicProducer.lambda$0(BasicProducer.java:36)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.eventprocessing.BasicProducer.safeProduce(BasicProducer.java:36)
	at mdz.eventprocessing.BasicProducer.produce(BasicProducer.java:42)
	at mdz.eventprocessing.Buffer.purge(Buffer.java:74)
	at mdz.ccuhistorian.Historian$_closure1.doCall(Historian.groovy:84)
	at mdz.ccuhistorian.Historian$_closure1.doCall(Historian.groovy)
	at mdz.ccuhistorian.ExtendedStorage$_fireOnRead_closure1.doCall(ExtendedStorage.groovy:141)
	at mdz.ccuhistorian.ExtendedStorage.fireOnRead(ExtendedStorage.groovy:141)
	at mdz.ccuhistorian.ExtendedStorage.getDataPointsOfInterface(ExtendedStorage.groovy:48)
	at mdz.ccuhistorian.Historian.update(Historian.groovy:148)
	at mdz.ccuhistorian.Historian$_updateDataPointMeta_closure3$_closure12.doCall(Historian.groovy:112)
	at mdz.ccuhistorian.Historian$_updateDataPointMeta_closure3$_closure12.doCall(Historian.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Historian$_updateDataPointMeta_closure3.doCall(Historian.groovy:108)
	at mdz.ccuhistorian.Historian.updateDataPointMeta(Historian.groovy:107)
	at mdz.ccuhistorian.Historian$_run_closure2.doCall(Historian.groovy:101)
	at mdz.ccuhistorian.Historian$_run_closure2.doCall(Historian.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Historian.run(Historian.groovy:100)
Caused by: java.lang.IllegalStateException: File corrupted in chunk 284271, expected page length 4..4096, got 976367664 [1.4.199/6]
	at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
	at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1055)
	at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
	at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
	at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
	at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
	at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:793)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:401)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
	at org.h2.mvstore.db.MVTableEngine$Store.open(MVTableEngine.java:162)
	... 43 more`

mein grundsystem ist ein rpi3 mit raspberrymatic  mit 3.51.6.202002029

ich lass es mal so stehen. mit welchen debugdaten kann ich unterstützen?

 folgende config ist aktiv:

`
logSystem.fileLevel=Level.INFO
logSystem.fileName='/var/log/ccu-historian-%g.log'
logSystem.fileLimit=1000000
logSystem.fileCount=5
logSystem.binRpcLevel=Level.INFO
database.dir='/media/usb0/ccu-historian'
database.webEnable=true
database.webPort=8083
database.webAllowOthers=true
database.pgEnable=true
database.pgPort=5435
database.pgAllowOthers=true
webServer.port=8082
webServer.historianAddress='10.0.0.10'
webServer.dir='/usr/local/addons/ccu-historian/ccu-historian/webapp'
webServer.logLevel=Level.INFO
devices.device1.type=CUSTOM_CCU
devices.device1.address='127.0.0.1'
devices.device1.plugin1.type=BIDCOS_RF
devices.device1.plugin2.type=HMIP_RF
devices.historianAddress='127.0.0.1'
historian.metaCycle=60*1000
historian.bufferTime=60*1000
base.scriptDir='/usr/local/addons/ccu-historian'
webServer.menuLinks.link1.text='H2-HighChart'
webServer.menuLinks.link1.address='/custom/h2-highchart/H2-HighChart.gy'
`

grüße
ori

**Comment by oriziena** [comment]
... okay... meine historian db hats zerlegt und ich finde den fehler auch nicht...
neu initialisiert und schwups geht auch 2.4.0 ... => closed!

**Comment by oriziena** [comment]
@mdzio die internen counter werden nun angezeigt!... teste auch die restlichen funktionen im zusammenhang mit meinem grafana durch... erstellte ggf. neue tickets, falls ich was finde! danke!
