### ISSUE TITLE
Parallelbetrieb mit ioBroker auf demselben Rechner (Exception: Unexpected end of stream)

### ISSUE THREAD

**Issue by lichtmannf** [mdzio/ccu-historian#219]
Hallo,

Seitdem ich der Historian auf eine rpi installiert habe, bekomme ich folgende Fehlermeldung nach einem bestimmen Zeit:

2020-04-29 21:20:44|SEVERE |Exception: Unexpected end of stream
2020-04-29 21:20:44|SEVERE |Detail: java.io.IOException: Unexpected end of stream
        at mdz.hc.itf.binrpc.BinRpcClient.receive(BinRpcClient.groovy:118)
        at mdz.hc.itf.binrpc.BinRpcClient.call(BinRpcClient.groovy:144)
        at mdz.hc.itf.hm.HmBinRpcInterface.init(HmBinRpcInterface.groovy:124)
        at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3$_closure4.doCall(HmReinitTask.groovy:83)
        at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3$_closure4.call(HmReinitTask.groovy)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3.doCall(HmReinitTask.groovy:82)
        at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3.call(HmReinitTask.groovy)
        at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1.doCall(HmReinitTask.groovy:77)
        at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1.call(HmReinitTask.groovy)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.hc.itf.hm.HmReinitTask.checkInterfaces(HmReinitTask.groovy:73)

Danach läuft der Historian nicht mehr.

Datenquelle is eine CCU3. Auf dem rpi läfut auch eine Instanz von ioBroker.

Soll ich anderes anpassen?

Danke.

**Comment by mdzio** [comment]
Der CCU-Historian hat eine Anfrage an die CCU geschickt. Die CCU bricht die Antwort aber ab. 
Der Fehler tritt nicht auf, wenn Historian und ioBroker auf verschiedenen Rechnern laufen?

**Comment by lichtmannf** [comment]
Hallo Mathias,

danke für Deine Antwort.

Der Fehler tritt nicht auf, wenn Historian und ioBroker auf verschiedenen Rechnern laufen. Ich habe der Historian auf meinem Windows Laptop laufen lassen und der hat für zwei Tage Problemlos funktioniert.

Viele Grüße

**Comment by mdzio** [comment]
Vielleicht kann die CCU den Historian und ioBroker nicht direkt unterscheiden, wenn sie auf demselben Rechner laufen.

Eventuell hilft die Konfigurationsoption _devices.device1.prefix_:
```
devices.device1.prefix='Historian'
```

Dann wird bei der Registrierung an der CCU noch dieser Prefix hinzugefügt, den ioBroker auf keinen Fall verwendet.

Allerdings werden dann alle Datenpunkte nochmal neu erkannt und mit diesem Prefix in der Datenbank eingetragen. Aber vielleicht könntest Du das testweise mal machen.

**Comment by lichtmannf** [comment]
HI Mathias, 

ich habe folgende Szenarios konfiguriert:

1. Historian as Service UND denPrefix im Historian Config eingestellt: Hatte auch den gleichen Fehlermeldung im Historian Log und nachher kam der Alarm vom Watchdog im CCU.

2. Historian als normaler Prozess (mit nohup) UND den Prefix im Historian Config eingestellt: nach 2 Tage, keine Fehlermeldung. Troztdem wollte ich ohne Prefix es testen (wegen den existierten Daten).

3. Historian als normaler Prozess (mit nohup) OHNE den Prefix im Historian Config: Fehlermeldung und folgende Info im Console vom Historian (letzte Zeilen im Datei):

2020-05-17 01:58:38
50066.599976
0
2020-05-17 01:58:38
65293.199974
0
2020-05-13 13:54:58
false
0
2020-05-13 13:54:58
false
0
2020-05-17 01:58:38
50066.599976
2020-05-17 02:00:00|FINEST |Checking backup time
2020-05-17 02:00:04|FINER  |Watchdog is triggered
2020-05-17 02:00:04|FINER  |Executing script:
                        var prg=dom.GetObject(ID_PROGRAMS).Get("Watch Historian");
                        if (prg) { prg.ProgramExecute(); WriteLine("0"); }
                        else { WriteLine("1"); }
2020-05-17 02:00:04|FINER  |Response: 0
2020-05-17 02:00:17|FINER  |Checking timeouts
2020-05-17 02:00:17|FINE   |system.multicall() with 1 item(s) received
2020-05-17 02:00:17|FINE   |event(BidCos-RF, CENTRAL, PONG, hm-rpc.0) call received
2020-05-17 02:00:17|FINER  |Event received: BidCos-RF.CENTRAL.PONG, Sun May 17 02:00:17 CEST 2020, hm-rpc.0, 2
2020-05-17 02:00:17|FINE   |Discarding ping response
2020-05-17 02:00:18|FINEST |Sleeping


Und nach fast 6 Minuten, kam den Alarm:
![image](https://user-images.githubusercontent.com/63543231/82139665-e158dd80-9829-11ea-930b-4955b23c2dd0.png)


Weißt du Warum ist der Historiam im "Sleeping Mode" gegangen? 

Danke und viele Grüße aus Aachen.

**Comment by mdzio** [comment]
Vorab: Die Meldung "Sleeping" wird vom Historian durchgängig alle 20-30 Sekunden geschrieben. Wenn sie nicht kommt, liegt ein Problem vor.

Die restliche Fehlerbeschreibung muss ich mir im Detail nochmal ansehen.

**Comment by mdzio** [comment]
Ist denn in den Fällen 1 und 3 der Historian-Prozess noch vorhanden?

**Comment by lichtmannf** [comment]
Fall 1: nein
Fall 3: nein

**Comment by lichtmannf** [comment]
> 
> 
> Vorab: Die Meldung "Sleeping" wird vom Historian durchgängig alle 20-30 Sekunden geschrieben. Wenn sie nicht kommt, liegt ein Problem vor.
> 
> Die restliche Fehlerbeschreibung muss ich mir im Detail nochmal ansehen.

Verstehe. Die Frage war nur, weil das die letzte Zeile im Log war.

**Comment by mdzio** [comment]
Aus den Log-Meldungen ist nicht ersichtlich, warum der CCU-Historian-Prozess in den Fällen 1 und 3 verschwinded. Die letzten Log-Meldungen sind wie im Normalbetrieb. Dann bleiben noch zwei Möglichkeiten: Der Prozess wird von außen terminiert (z.B. kill Befehl) oder die Java-VM hat ein ernstes Problem festgestellt. Dann sollte aber eine Datei hs_err_pid.log mit weiteren Informationen erstellt werden.

**Comment by mdzio** [comment]
Vielleicht sind Fehlermeldung im Log der CCU zu diesen Zeitpunkten noch hilfreich. Liegen welche vor?

**Comment by lichtmannf** [comment]
Leider es gitb keine hs_err_pid.log.

Aus dem Homematic Log (messages):

um 11:31 es hat angefangen, eine Fehlermeldung aufzutretten. Danach war der Historian um 14:03:29 tot (Watchdog) und auch die Fehlermeldungen im Datei "messages" haben aufgehört:

May 25 11:31:14 ccu3-webui user.err Sniffing Mode: XmlRpcClient error calling event({[methodName:"event",params:{"hm-rpc.0","MOTION0004:1","BRIGHTNESS",0}]}) on http://192.168.1.120:2001/RPC2:
May 25 11:31:14 ccu3-webui user.err Sniffing Mode: XmlRpc transport error
May 25 14:04:42 ccu3-webui user.err Sniffing Mode: XmlRpcClient error calling event({[methodName:"event",params:{"hm-rpc.0","MOTION0002:1","BRIGHTNESS",0}]}) on http://192.168.1.120:2001/RPC2:
May 25 14:04:42 ccu3-webui user.err Sniffing Mode: XmlRpc transport error

**Comment by mdzio** [comment]
Diese Fehlermeldungen werden aber durch ioBroker verursacht. Dies kann an `hm-rpc.0 `erkannt werden. Anscheinend ist ioBroker ebenfalls zu diesem Zeitpunkt nicht erreichbar. Das Fehlerbild ist also sehr komplex.

**Comment by lichtmannf** [comment]
Ich habe die Vermütung, dass das Problem ein "Out of Memory" issue sein könnte. Was hälst du davon? Wieviel heap sollte für den Historian allokiert werden? (Xmx, Xms).

**Comment by mdzio** [comment]
Dann müsste eigentlich auch eine Log-Meldung erscheinen. Du kannst den Speicher beispielsweise mit `-Xmx512m` auf 512 MB erhöhen.

**Comment by mdzio** [comment]
Auf Grund von Inaktivität schließe ich dieses Thema erst einmal. Bei bedarf kann es wieder eröffnet werden.
