### ISSUE TITLE
Datenpunktliste: Spalten mit Zeitstempel und aktuellem Wert

### ISSUE THREAD

**Issue by blackbasket** [mdzio/ccu-historian#276]
Hi @mdzio,

in den ersten Versionen des Historian, die ich verwendet habe, gab es die Ansicht von "letzte Kommunikation" und "Wert" in der Datenpunktliste. Seit v2 (?) ist dies nicht mehr so. Gibt es dafür einen Grund?

Aktuell passe ich die index.gy nach einem Update immer entsprechend an. Ggf. wäre dies aber genrell interessant, sodass man dies wieder ins default übernimmt.

Was meinst du dazu?

LG,
Marcel

**Comment by mdzio** [comment]
Es wurde aus zwei Gründen heraus genommen: Die Tabelle wurde zu breit und gerade bei vielen Datenpunkten ist die Performance eingebrochen. Und gerade diese Seite sollte schnell laden.

Ich kann aber eine Konfigurationsoption einbauen, um die Spalten bei Bedarf wieder einzublenden.

**Comment by blackbasket** [comment]
Hallo Mathias,

das wäre super :)

LG,
Marcel

**Comment by mdzio** [comment]
Welche Anpassungen nimmst Du den vor? Dann kann ich sie als Vorlage nehmen.

**Comment by blackbasket** [comment]
Hallo Mathias,

anbei einmal das gesamte File.
[index.txt](https://github.com/mdzio/ccu-historian/files/6034147/index.txt)

Änderungen sind lt. Diff:
Zeile 20
`import static mdz.ccuhistorian.webapp.TextFormat.*`

Zeile 120:
`th class:'hidden-xs hidden-sm hidden-md', 'Gewerk',`

Zeile 126-129:
`th 'Kommunikation',
						'data-toggle':'tooltip', title:'Letzte erfolgreiche Kommunikation'
					th 'Wert',
						'data-toggle':'tooltip', title:'Letzter Wert'`

Zeile 134:
`def last=database.getLast(dp)`

Zeile 151:
`td class:'hidden-xs hidden-sm hidden-md', dp.attributes.function`

Zeile 154+155:
`td formatDate(last?.timestamp)
						td format(last?.value)`

LG,
Marcel

**Comment by mdzio** [comment]
Die Konfigurationsoption lautet: `webServer.showLastValue=true`

**Comment by blackbasket** [comment]
Danke :) ich werde es nächste Woche mal testen... ich hatte die letzten Monate Probleme, weshalb ich auch den Historian komplett gekickt habe ;)

**Comment by blackbasket** [comment]
Funktioniert super :)

**Comment by MichaelN0815** [comment]
RM 3.59.6.20210807
CCU-Historian 2.6.0
setze ich die Option webServer.showLastValue=true
dann stürzt CCU-Historian mit dieser Meldung im LOG ab:
2021-08-31 09:11:17|SEVERE |Exception: Configuration file /usr/local/addons/ccu-historian/ccu-historian.config is invalid
2021-08-31 09:11:17|SEVERE |Detail: java.lang.Exception: Configuration file /usr/local/addons/ccu-historian/ccu-historian.config is invalid
	at mdz.ccuhistorian.Configuration.readFile(Configuration.groovy:140)
	at mdz.ccuhistorian.Main.start(Main.groovy:86)
	at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy:77)
	at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Main.run(Main.groovy:77)
	at mdz.ccuhistorian.Main.main(Main.groovy:45)
Caused by: groovy.lang.MissingPropertyException: No such property: showLastValue for class: mdz.ccuhistorian.webapp.WebServerConfig
	at Config.run(Config:26)
	at mdz.ccuhistorian.Configuration.readFile(Configuration.groovy:138)

**Comment by mdzio** [comment]
Diese Verbesserung gibt es erst ab Version 2.7.0-beta.1 (siehe oben rechts der Milestone).
