### ISSUE TITLE
java.nio.BufferUnderflowException bei Creating backup of database to file

### ISSUE THREAD

**Issue by armin34320** [mdzio/ccu-historian#284]
Anbei der letzte Output des Logs.
Die Medung kommt ca. jede Stunde.

2021-04-21 09:00:00|INFO   |Creating backup of database to file /media/usb1/backup/ccu-historian-db-21.gz
2021-04-21 09:00:55|SEVERE |Exception: General error: "java.nio.BufferUnderflowException"; SQL statement:
SCRIPT DROP TO ? COMPRESSION GZIP [50000-199]
2021-04-21 09:00:55|SEVERE |Detail: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.nio.BufferUnderflowException"; SQL statement:
SCRIPT DROP TO ? COMPRESSION GZIP [50000-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:502)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.get(DbException.java:194)
        at org.h2.message.DbException.convert(DbException.java:347)
        at org.h2.command.Command.executeQuery(Command.java:219)
        at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:243)
        at mdz.ccuhistorian.Database.createBackup(Database.groovy:745)
        at mdz.ccuhistorian.Database$_checkBackupTime_closure8.doCall(Database.groovy:731)
        at mdz.ccuhistorian.Database$_checkBackupTime_closure8.doCall(Database.groovy)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.ccuhistorian.Database.checkBackupTime(Database.groovy:727)
Caused by: java.nio.BufferUnderflowException
        at org.h2.mvstore.db.ValueDataType.readValue(ValueDataType.java:632)
        at org.h2.mvstore.db.ValueDataType.readValue(ValueDataType.java:650)
        at org.h2.mvstore.db.ValueDataType.read(ValueDataType.java:213)
        at org.h2.mvstore.tx.VersionedValueType.read(VersionedValueType.java:65)
        at org.h2.mvstore.Page$Leaf.readPayLoad(Page.java:1551)
        at org.h2.mvstore.Page.read(Page.java:695)
        at org.h2.mvstore.Page.read(Page.java:238)
        at org.h2.mvstore.MVStore.readPage(MVStore.java:2187)
        at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
        at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
        at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
        at org.h2.mvstore.tx.TransactionMap$TMIterator.fetchNext(TransactionMap.java:711)
        at org.h2.mvstore.tx.TransactionMap$TMIterator.next(TransactionMap.java:752)
        at org.h2.mvstore.db.MVPrimaryIndex$MVStoreCursor.next(MVPrimaryIndex.java:474)
        at org.h2.command.dml.ScriptCommand.generateInsertValues(ScriptCommand.java:404)
        at org.h2.command.dml.ScriptCommand.query(ScriptCommand.java:299)
        at org.h2.command.CommandContainer.query(CommandContainer.java:145)
        at org.h2.command.Command.executeQuery(Command.java:202)
        ... 8 more
root@schl_ccu3:/var/log#

**Comment by armin34320** [comment]
Hat jemand eine Idee was die Ursache ist oder man dagegen machen kann?

**Comment by mdzio** [comment]
Der Fehler tritt bei der automatischen Erstellung des Backups auf. Mit der Konfigurationsoption `database.backup` ist anscheinend ein stündliches Backup eingestellt. Ist genug Plattenplatz für das Backup vorhanden?

Eventuell hilft eine Kompaktierung der Datenbank mit der Option `-compact`.

**Comment by armin34320** [comment]
Hallo mdzio,
ja das weiss ich. Wird beim Backup generiert. Backup wird jeden Tag automatisch erzeugt. Nach dem ersten Auftreten des Fehlers wird offensichtlich jede Stunde ein neuer Versuch gestartet.

Platz ist genug auf dem USB Stick.

Kurz nach Auftreten dieses Fehlers (ca. nach einem Tag) ist die Datenbank dann defekt. Fehlermeldung 'Exception ... File corrupted'

**Comment by armin34320** [comment]
Woran kann das liegen. Ist ein USB Stick nicht für die Historian Datenbank geeignet oder ist da ein Bug im CCU-Historian?

**Comment by mdzio** [comment]
Es wird häufig berichtet, dass USB-Sticks unter der andauernden Verwendung irgendwann Fehler produzieren. Ein paar[ Tipps dazu sind hier](https://github.com/mdzio/ccu-historian/wiki#paket-für-ccu3-und-raspberrymatic) zu finden.

Für den CCU-Historian wird generell eine USB-SSD empfohlen. 

Funktioniert denn ein `-compact` ? Dadurch wird die komplette Datenbank einmal neu organisiert und geschrieben.

**Comment by armin34320** [comment]
Ja, hab ich auch schon gelesen. 

Meine Node-Red Config Daten sind aber immer ok.

Werde demnächst dann mal eine USB-SSD kaufen.

Wo muss ich denn die Option '-compact' angeben?

**Comment by mdzio** [comment]
Die Option muss auf der Kommandozeile beim Start des CCU-Historians angegeben werden. Ein [Beispiel ist hier](https://github.com/mdzio/ccu-historian/wiki/CCU3-AddOn) zu finden.

**Comment by mdzio** [comment]
Den Fehler kann ich leider nicht reproduzieren.
