### ISSUE TITLE
Database recovery schlägt mit IllegalStateExeption Exception fehl

### ISSUE THREAD

**Issue by JoeKN82** [mdzio/ccu-historian#285]
Hallo,
ich habe leider eine Korrupte Datenbank und habe versucht sie zu retten, wie es in der Wiki beschrieben ist, allerding kommt es dann zu einer Exception:

C:\temp\CCUHistorian> java -cp lib\h2-1.4.199.jar org.h2.tools.Recover -dir data -db history
Exception in thread "main" java.lang.IllegalStateException: File corrupted in chunk 12080962, expected page length 4..192, got -1263530496 [1.4.199/6]
        at org.h2.mvstore.DataUtils.newIllegalStateException(DataUtils.java:883)
        at org.h2.mvstore.MVStore.readBufferForPage(MVStore.java:1055)
        at org.h2.mvstore.MVStore.readPage(MVStore.java:2186)
        at org.h2.mvstore.MVMap.readPage(MVMap.java:554)
        at org.h2.mvstore.Page$NonLeaf.getChildPage(Page.java:1086)
        at org.h2.mvstore.Cursor.hasNext(Cursor.java:53)
        at org.h2.mvstore.MVStore.readStoreHeader(MVStore.java:793)
        at org.h2.mvstore.MVStore.<init>(MVStore.java:401)
        at org.h2.mvstore.MVStore$Builder.open(MVStore.java:3343)
        at org.h2.mvstore.MVStoreTool.info(MVStoreTool.java:347)
        at org.h2.tools.Recover.process(Recover.java:344)
        at org.h2.tools.Recover.runTool(Recover.java:195)
        at org.h2.tools.Recover.main(Recover.java:158)
PS C:\temp\CCUHistorian>

Bitte mal nachschauen ob das ein Bug ist, und man die Datenbank noch retten kann. Die enthält von mehereren Jahren Daten und ist ca. 14 GB groß

**Comment by mdzio** [comment]
Bitte mal den CCU-Historian mit `-createscript` starten:
```
java -jar ccu-historian.jar -createscript backup.sql
```

Du kannst auch mal das Recover-Werkzeug einer neueren Version der H2-Datenbank ausprobieren. Die neue Version kannst Du [hier herunter laden](https://h2database.com/h2-2019-10-14.zip). Dort findest Du die `h2-1.4.200.jar`. Diese kannst Du wie oben starten.

Wenn auch das fehl schlägt, sieht es leider nicht gut aus.

**Comment by JoeKN82** [comment]
2021-05-13 07:41:33|INFO   |CCU-Historian V2.6.0
2021-05-13 07:41:33|INFO   |(C)MDZ (info@ccu-historian.de)
2021-05-13 07:41:35|INFO   |Starting base services
2021-05-13 07:41:35|INFO   |Starting dump of database
2021-05-13 07:47:05|SEVERE |Exception: No signature of method: org.codehaus.groovy.runtime.MethodClosure.dump() is applicable for argument types: (mdz.ccuhistorian.DatabaseConfig, String) values: [mdz.ccuhistorian.DatabaseConfig@7b303352, backup.sql]
Possible solutions: dump(), run(), grep(), wait(), call(), find()
2021-05-13 07:53:07|SEVERE |Detail: groovy.lang.MissingMethodException: No signature of method: org.codehaus.groovy.runtime.MethodClosure.dump() is applicable for argument types: (mdz.ccuhistorian.DatabaseConfig, String) values: [mdz.ccuhistorian.DatabaseConfig@7b303352, backup.sql]
Possible solutions: dump(), run(), grep(), wait(), call(), find()
        at mdz.ccuhistorian.OfflineMaintenanceSystem$_closure1$_closure2.doCall(OfflineMaintenanceSystem.groovy:39)
        at mdz.ccuhistorian.OfflineMaintenanceSystem$_closure1$_closure2.doCall(OfflineMaintenanceSystem.groovy)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.ccuhistorian.OfflineMaintenanceSystem$_closure1.doCall(OfflineMaintenanceSystem.groovy:39)
        at mdz.ccuhistorian.OfflineMaintenanceSystem$_closure1.doCall(OfflineMaintenanceSystem.groovy)


Hilft leider auch nicht... Trotzdem danke.
