### ISSUE TITLE
high RAM usage mit 2.7.1

### ISSUE THREAD

**Issue by MichaelN0815** [mdzio/ccu-historian#307]
Ich habe CCU-Historian auf einer Original CCU als AddOn unter RM 3.61.5 laufen
Seit heute bekomme ich Meldungen über hohen Speicherverbrauch von RM.

In TOP ist dieser Eintrag auffällig
`1	1170	1171	?	root	3.7g	S	588m	/opt/java/bin/java	"-Xmx512m   	-Djava.util.prefs.userRoot=/usr/local/addons/ccu-historian	-Djava.util.prefs.systemRoot=/usr/local/addons/ccu-historian	-jar	/usr/local/addons/ccu-historian/ccu-historian/ccu-historian.jar	-config	/usr/local/addons/ccu-historian/ccu-historian.config	-loglevel	off"								`

Da ich vorher nie Probleme mi dem Speicherverbrauch hatte, habe ich das auch vorher nie überprüft. Ich kann also nicht sagen, ob es einfach nur an einer langsam gewachsenen Datenbank liegt. 

Aber ich habe erst vor kurzem auf CCU-Historian 2.7.1 upgedatet; vorher Version 2.6 ohne Probleme gefahren. 

Daher die Frage, ob sich mit 2.7.1 irgendwas mit dem Speicherbedarf geändert hat und was ich machen kann, um den Speicherbedarf ggf. wieder zu reduzieren.

**Comment by MichaelN0815** [comment]
Nach dem Neustart von CCU-Historian ist der Speicherbedarf um fast 30% gesunken. 

Anbei das Log-File bis zum Restart:

```
2021-11-13 16:21:50|INFO   |Starting base services
2021-11-13 16:21:51|INFO   |Connecting to database
2021-11-13 16:22:15|INFO   |Starting database web server
2021-11-13 16:22:16|INFO   |Setting up device 1
2021-11-13 16:22:17|INFO   |Creating HM script client for http://127.0.0.1:8181/tclrega.exe
2021-11-13 16:22:17|INFO   |Setting up plug-in 1
2021-11-13 16:22:18|INFO   |Configured following interfaces: BidCos-RF, HmIP-RF, SysVar, CUxD
2021-11-13 16:22:18|INFO   |Starting interfaces
2021-11-13 16:22:18|INFO   |Starting BIN-RPC server on port 2099
2021-11-13 16:22:18|INFO   |Starting XML-RPC server on port 2098
2021-11-13 16:22:24|INFO   |Connecting to 127.0.0.1:8701
2021-11-13 16:22:24|INFO   |Starting historian
2021-11-13 16:22:25|INFO   |Starting web server
2021-11-13 16:22:26|INFO   |Logging initialized @54788ms to org.eclipse.jetty.util.log.JavaUtilLog
2021-11-13 16:22:26|INFO   |jetty-9.4.41.v20210516; built: 2021-05-16T23:56:28.993Z; git: 98607f93c7833e7dc59489b13f3cb0a114fb9f4c; jvm 1.8.0_312-b07
2021-11-13 16:22:28|INFO   |NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2021-11-13 16:22:28|INFO   |DefaultSessionIdManager workerName=node0
2021-11-13 16:22:28|INFO   |No SessionScavenger set, using defaults
2021-11-13 16:22:28|INFO   |node0 Scavenging every 600000ms
2021-11-13 16:22:29|INFO   |Started o.e.j.w.WebAppContext@d8948cd{CCU-Historian Web Application,/,file:///usr/local/addons/ccu-historian/ccu-historian/webapp/,AVAILABLE}
2021-11-13 16:22:29|INFO   |Started ServerConnector@7906578e{HTTP/1.1, (http/1.1)}{0.0.0.0:8082}
2021-11-13 16:22:29|INFO   |Started @58196ms
2021-11-13 16:22:29|INFO   |Web server port: 8082
2021-11-13 16:22:46|WARNING|Unknown system variable SysVar.8261.VALUE
2021-11-13 16:22:46|WARNING|Unknown system variable SysVar.11232.VALUE
2021-11-13 16:22:46|WARNING|Unknown system variable SysVar.9093.VALUE
2021-11-13 16:22:46|WARNING|Unknown system variable SysVar.10702.VALUE
2021-11-13 16:22:46|WARNING|Unknown system variable SysVar.10701.VALUE
2021-11-13 16:22:46|WARNING|Unknown system variable SysVar.1445.VALUE
2021-11-13 16:22:46|WARNING|Unknown system variable SysVar.13038.VALUE
2021-11-13 16:22:46|WARNING|Unknown system variable SysVar.13039.VALUE
2021-11-13 16:22:47|WARNING|Device CUxD.CUX9002003:0.UNREACH does not exist
2021-11-13 16:22:47|INFO   |Connecting to 127.0.0.1:8701
2021-11-13 16:22:47|WARNING|Device CUxD.CUX9002003:1.ABS_HUMIDITY does not exist
2021-11-13 16:22:48|INFO   |Connecting to 127.0.0.1:8701
2021-11-13 16:22:48|WARNING|Device CUxD.CUX9002003:1.DEW_POINT does not exist
2021-11-13 16:22:48|INFO   |Connecting to 127.0.0.1:8701
2021-11-13 16:22:48|WARNING|Device CUxD.CUX9002003:1.HUMIDITY does not exist
2021-11-13 16:22:48|INFO   |Connecting to 127.0.0.1:8701
2021-11-13 16:22:48|WARNING|Device CUxD.CUX9002003:1.HUMIDITYF does not exist
2021-11-13 16:22:48|INFO   |Connecting to 127.0.0.1:8701
2021-11-13 16:22:48|WARNING|Device CUxD.CUX9002003:1.HUM_MAX_24H does not exist
2021-11-13 16:22:48|INFO   |Connecting to 127.0.0.1:8701
2021-11-13 16:22:48|WARNING|Device CUxD.CUX9002003:1.HUM_MIN_24H does not exist
2021-11-13 16:22:49|INFO   |Connecting to 127.0.0.1:8701
2021-11-13 16:22:49|WARNING|Device CUxD.CUX9002003:1.TEMPERATURE does not exist
2021-11-13 16:22:49|INFO   |Connecting to 127.0.0.1:8701
2021-11-13 16:22:49|WARNING|Device CUxD.CUX9002003:1.TEMP_MAX_24H does not exist
2021-11-13 16:22:49|INFO   |Connecting to 127.0.0.1:8701
2021-11-13 16:22:49|WARNING|Device CUxD.CUX9002003:1.TEMP_MIN_24H does not exist
2021-11-13 16:22:49|INFO   |Connecting to 127.0.0.1:8701
2021-11-13 16:22:49|WARNING|Device CUxD.CUX9002003:2.SET_INVERT does not exist
2021-11-13 16:22:49|INFO   |Connecting to 127.0.0.1:8701
2021-11-13 16:22:49|WARNING|Device CUxD.CUX9002003:2.STATE does not exist
2021-11-13 16:31:27|INFO   |Groovy servlet initialized on groovy.util.GroovyScriptEngine@4032b37.
2021-11-13 21:48:49|INFO   |Connecting to 127.0.0.1:8701
2021-11-15 18:37:52|SEVERE |Exception: Unexpected end of stream
2021-11-15 18:37:52|SEVERE |Detail: java.io.IOException: Unexpected end of stream
	at mdz.hc.itf.binrpc.BinRpcClient.receive(BinRpcClient.groovy:118)
	at mdz.hc.itf.binrpc.BinRpcClient.call(BinRpcClient.groovy:144)
	at mdz.hc.itf.hm.HmBinRpcInterface.init(HmBinRpcInterface.groovy:124)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3$_closure4.doCall(HmReinitTask.groovy:83)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3$_closure4.call(HmReinitTask.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3.doCall(HmReinitTask.groovy:82)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3.call(HmReinitTask.groovy)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1.doCall(HmReinitTask.groovy:77)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1.call(HmReinitTask.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.hc.itf.hm.HmReinitTask.checkInterfaces(HmReinitTask.groovy:73)
2021-11-19 01:57:58|INFO   |Connecting to 127.0.0.1:8701
2021-11-20 02:56:29|SEVERE |Exception: Unexpected end of stream
2021-11-20 02:56:29|SEVERE |Detail: java.io.IOException: Unexpected end of stream
	at mdz.hc.itf.binrpc.BinRpcClient.receive(BinRpcClient.groovy:118)
	at mdz.hc.itf.binrpc.BinRpcClient.call(BinRpcClient.groovy:144)
	at mdz.hc.itf.hm.HmBinRpcInterface.init(HmBinRpcInterface.groovy:124)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3$_closure4.doCall(HmReinitTask.groovy:83)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3$_closure4.call(HmReinitTask.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3.doCall(HmReinitTask.groovy:82)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3.call(HmReinitTask.groovy)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1.doCall(HmReinitTask.groovy:77)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1.call(HmReinitTask.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.hc.itf.hm.HmReinitTask.checkInterfaces(HmReinitTask.groovy:73)
2021-11-20 02:56:59|INFO   |Connecting to 127.0.0.1:8701
2021-11-22 04:33:10|INFO   |Historian: Creating data point SysVar.40122.VALUE
2021-11-22 10:23:33|SEVERE |Exception: Unexpected end of stream
2021-11-22 10:23:33|SEVERE |Detail: java.io.IOException: Unexpected end of stream
	at mdz.hc.itf.binrpc.BinRpcClient.receive(BinRpcClient.groovy:118)
	at mdz.hc.itf.binrpc.BinRpcClient.call(BinRpcClient.groovy:144)
	at mdz.hc.itf.hm.HmBinRpcInterface.init(HmBinRpcInterface.groovy:124)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3$_closure4.doCall(HmReinitTask.groovy:83)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3$_closure4.call(HmReinitTask.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3.doCall(HmReinitTask.groovy:82)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3.call(HmReinitTask.groovy)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1.doCall(HmReinitTask.groovy:77)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1.call(HmReinitTask.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.hc.itf.hm.HmReinitTask.checkInterfaces(HmReinitTask.groovy:73)
2021-11-22 12:33:31|INFO   |Historian: Creating data point SysVar.40125.VALUE 
```

**Comment by mdzio** [comment]
Der Speicherverbrauch des CCU-Historians ist klar begrenzt durch die Kommandozeilenoption -Xmx512m. Dadurch darf der CCU-Historian 512 MB verwenden. Hinzu kommen ca. 100 MB je nach eingesetzter Java-VM. Das entspricht etwa den 588 MB, die als RSS angezeigt werden.

Ich nehme an, dass Dein System nur 1 GB RAM insgesamt besitzt? Dann solltest Du besser -Xmx256m in dem Startup-Skript (Datei /usr/local/etc/config/rc.d/ccu-historian) setzen. Dies ist auch [im Handbuch beschrieben](https://github.com/mdzio/ccu-historian/wiki/CCU3-AddOn#speicherverbrauch-verringern).

Wieviel freier Speicher noch vorhanden ist, hängt natürlich von vielen Faktoren ab. Auch wenn der Speicherverbrauch vom CCU-Historian begrenzt ist, kann der freie Speicher bei Aktionen des CCU-Historians sinken. Dies hängt damit zusammen, dass das Betriebssystem Linux entscheidet, weiteren Speicher für die Optimierung der Lese-/Schreibzugriffe auf die Datenbank zu verwenden. Darauf hat der CCU-Historian keinen Einfluss. Dieser kann dann nach einiger Zeit auch wieder freigegeben werden.

**Comment by MichaelN0815** [comment]
Ich lasse Historian nun mit der Option Xmx256m laufen, es beansprucht (aktuell) trotzdem 501 MB (von 1GB):
`1 18347 18348 ?      root     3.4g S    501m /opt/java/bin/java -Xmx256m -Djava.util.prefs.userRoot=/usr/local/addons/ccu-historian -Djava.util.prefs.systemRoot=/usr/local/addons/ccu-historian -jar /usr/local/addons/ccu-historian/ccu-historian/ccu-historian.jar -config /usr/local/addons/ccu-historian/ccu-historian.config -loglevel off`

Das sollte, wenn ich deine Erläuterungen richtig verstehe, doch so nicht passieren?!

**Comment by mdzio** [comment]
Ja, da stimme ich zu.
Probiere bitte mal die weitere Reduzierung des Speichers auf `-Xmx128m`. Oder Du solltest ein größeren Raspberry kaufen.

**Comment by MichaelN0815** [comment]
Solange der Speicherbedarf brav bei ~50% des Speichers verbleibt, ist ja alles OK. 
Ein Raspberry mit mehr Speicher würde ja auch nichts nützen, wenn der Speicherbedarf immer weiter wächst. Das Problem würde nur später auftreten. Ich werde beobachten und mich melden, wenn ich etwas in der Richtung beobachte.

**Comment by MichaelN0815** [comment]
Ich würde dieses Issue gerne nochmal öffnen. Die Option -Xmx scheint ignoriert zu werden. CCU Historian verbraucht so viel Speicher, wie es braucht. Zumindest erscheint es mir so.

Mit der Xmx512M Option: 
![Unbenannt](https://user-images.githubusercontent.com/68965895/148386603-47839e05-ac73-4da9-a456-80ab44f0229e.JPG)

Mit Xmx384M, 3 Stunden nach dem Neustart:
![Unbenannt2](https://user-images.githubusercontent.com/68965895/148386699-50064af6-5de7-4eca-aa93-045717a8ed6d.JPG)

Oder zeigt Monit Quatsch an?
