### ISSUE TITLE
Absturz bei HTTP-Status 503

### ISSUE THREAD

**Issue by MStrecke** [mdzio/ccu-historian#318]
Bei mir läuft im Augenblick ein RaspberryMatic mit einem HmIP-RFUSB (der Homematic***IP***-Funkstick).
Der CCU-Historian läuft auf einem anderen Linux-Rechner, **nicht** in der Zentrale.

Durch diese Hardwarekonfiguration sind an der Zentrale nur HomematicIP-Geräte angemeldet.
Ein Anlernen von Homematic-NonIP wird mangels entsprechender Funk-Hardware gar nicht erst angeboten.

Der Historian versucht über http://192.168.0.XX:2001 die Non-IP-Geräte abzufragen, was der Server in der Zentrale mit einer HTTP-Fehlermeldung 503 (Service unavailable) quittiert, was den Historian alle 30 s zum Absturz bringt aus dem er sich wieder hochrappelt.
(Eine HTTP-Fehlermeldung ist eine gültige Kommunikation, d.h. die Ports sind offen, der Server wurde erreicht, aber der Dienst läuft auf dem Server nicht.)

Die Daten der angemeldeten Geräte in der Zentrale werden ausgelesen und können angezeigt werden.

Ich habe bis jetzt keine Möglichkeit gefunden dem Historian die Abfrage nach BidCos-RF-Geräten (via Port 2001) zu verbieten, damit er den Absturz vermeiden kann.

```
$ java -jar ccu-historian.jar 
2021-12-21 17:13:56|INFO   |CCU-Historian V2.8.1
2021-12-21 17:13:56|INFO   |(C)MDZ (info@ccu-historian.de)
2021-12-21 17:13:57|INFO   |Starting base services
2021-12-21 17:13:57|INFO   |Connecting to database
2021-12-21 17:13:57|INFO   |Starting database web server
2021-12-21 17:13:57|INFO   |Setting up device 1
2021-12-21 17:13:57|INFO   |Creating HM script client for http://192.168.0.XX:8181/tclrega.exe
2021-12-21 17:13:58|INFO   |Configured following interfaces: BidCos-RF, HmIP-RF, SysVar
2021-12-21 17:13:58|INFO   |Starting interfaces
2021-12-21 17:13:58|INFO   |Starting BIN-RPC server on port 2099
2021-12-21 17:13:58|INFO   |Starting XML-RPC server on port 2098
2021-12-21 17:13:58|SEVERE |Exception: Server returned HTTP response code: 503 for URL: http://192.168.0.XX:2001
2021-12-21 17:13:58|SEVERE |Detail: java.io.IOException: Server returned HTTP response code: 503 for URL: http://192.168.0.XX:2001
	at mdz.hc.itf.hm.HmXmlRpcClient.init(HmXmlRpcClient.groovy:55)
	at mdz.hc.itf.hm.HmXmlRpcInterface.init(HmXmlRpcInterface.groovy:123)
	at mdz.hc.itf.hm.HmXmlRpcInterface$_start_closure1.doCall(HmXmlRpcInterface.groovy:78)
	at mdz.hc.itf.hm.HmXmlRpcInterface$_start_closure1.doCall(HmXmlRpcInterface.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.hc.itf.hm.HmXmlRpcInterface.start(HmXmlRpcInterface.groovy:78)
	at mdz.hc.itf.Manager$_start_closure1.doCall(Manager.groovy:58)
	at mdz.hc.itf.Manager.start(Manager.groovy:56)
	at mdz.ccuhistorian.HistorianSystem.<init>(HistorianSystem.groovy:39)
	at mdz.ccuhistorian.Main.start(Main.groovy:100)
	at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy:77)
	at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Main.run(Main.groovy:77)
	at mdz.ccuhistorian.Main.main(Main.groovy:45)
2021-12-21 17:13:58|INFO   |Starting historian
2021-12-21 17:13:58|INFO   |Starting web server
2021-12-21 17:13:58|INFO   |Web server port: 8090
2021-12-21 17:18:58|SEVERE |Exception: Server returned HTTP response code: 503 for URL: http://192.168.0.XX:2001
2021-12-21 17:18:58|SEVERE |Detail: java.io.IOException: Server returned HTTP response code: 503 for URL: http://192.168.0.XX:2001
	at mdz.hc.itf.hm.HmXmlRpcClient.init(HmXmlRpcClient.groovy:55)
	at mdz.hc.itf.hm.HmXmlRpcInterface.init(HmXmlRpcInterface.groovy:123)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3$_closure4.doCall(HmReinitTask.groovy:83)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3$_closure4.call(HmReinitTask.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3.doCall(HmReinitTask.groovy:82)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3.call(HmReinitTask.groovy)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1.doCall(HmReinitTask.groovy:77)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1.call(HmReinitTask.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.hc.itf.hm.HmReinitTask.checkInterfaces(HmReinitTask.groovy:73)
2021-12-21 17:19:28|SEVERE |Exception: Server returned HTTP response code: 503 for URL: http://192.168.0.XX:2001
2021-12-21 17:19:28|SEVERE |Detail: java.io.IOException: Server returned HTTP response code: 503 for URL: http://192.168.0.XX:2001
	at mdz.hc.itf.hm.HmXmlRpcClient.init(HmXmlRpcClient.groovy:55)
	at mdz.hc.itf.hm.HmXmlRpcInterface.init(HmXmlRpcInterface.groovy:123)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3$_closure4.doCall(HmReinitTask.groovy:83)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3$_closure4.call(HmReinitTask.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3.doCall(HmReinitTask.groovy:82)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1$_closure3.call(HmReinitTask.groovy)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1.doCall(HmReinitTask.groovy:77)
	at mdz.hc.itf.hm.HmReinitTask$_checkInterfaces_closure1.call(HmReinitTask.groovy)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.hc.itf.hm.HmReinitTask.checkInterfaces(HmReinitTask.groovy:73)

... alle 30 Sekunden ...
```

**Comment by MStrecke** [comment]
I've just been made aware of the following work-around:

Choose `CUSTOM_CCU` and enumerate the plug-ins manually omitting `BidCos-RF`.

```
devices.device1.type=CUSTOM_CCU
devices.device1.plugin1.type=HMIP_RF
devices.device1.plugin2.type=CUXD
```

**Comment by MStrecke** [comment]
... und ein RaspberryMatic-Update später ...

Die allerneuste Version (3.61.7.20211218) von RaspberryMatic bringt ein Firmware-Update für den HmIP-RFUSB mit.
Hiermit kann dieser Stick nun sowohl Homematic- als auch HomematicIP-Geräte handhaben.
Auf jeden Fall sind jetzt beide Anlern-Bildschirme zu sehen.

Das bedeutet auch, dass die Nachfrage des CCU-Historian nicht mehr ins Leere läuft und der oben gezeigte Fehler nicht mehr auftritt.

Es wäre trotzdem nett gewesen, wenn jemand diese Exception abgefangen hätte.
