### ISSUE TITLE
Nicht lauffähig auf höheren Java-Versionen z.B. 17 (Unsupported class file major version 61)

### ISSUE THREAD

**Issue by alpha0x1omega** [mdzio/ccu-historian#336]
Hallo Mathias,

vielen Dank für die neue CCU Historian Version. Die alte lief auf meiner Synology DSM7 problemlos. Jetzt wollte ich umsteigen auf ccu-historian-dsm7-3.0.0.3.0-noarch.spk. Bekomme aber einen Fehler

Kannst du mir vielleicht einen Tipp geben.
Danke
Robert

2022-04-11 21:40:07|SEVERE |Exception: BUG! exception in phase 'semantic analysis' in source unit 'Config' Unsupported class file major version 61
2022-04-11 21:40:07|SEVERE |Detail: BUG! exception in phase 'semantic analysis' in source unit 'Config' Unsupported class file major version 61
        at mdz.ccuhistorian.Configuration.readFile(Configuration.groovy:138)
        at mdz.ccuhistorian.Main.start(Main.groovy:86)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy:77)
        at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.ccuhistorian.Main.run(Main.groovy:77)
        at mdz.ccuhistorian.Main.main(Main.groovy:45)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)

**Comment by alpha0x1omega** [comment]
Hallo Matthias,
bin  wieder zurück auf ccu-historian-dsm7-3.0.0.2.3 
Jetzt läuft wieder Historian. Also deine Empfehlung war gut.
Vielen Dank!

**Comment by mdzio** [comment]
Die Synology-Pakete habe ich nochmals in der [V3.0.1 Release](https://github.com/mdzio/ccu-historian/releases/tag/3.0.1) angepasst. Einfach nochmal neu herunterladen und installieren.
