### ISSUE TITLE
CCU-Historian V3.0.1 - Problem auf Synology DSM 7 mit Java 17.0.2 

### ISSUE THREAD

**Issue by DidiTheE** [mdzio/ccu-historian#339]
Hallo Mathias,
besteht das Problem mit Java 17 auf dem DSM 7 weiterhin? Oder muss ich bei der Installation noch etwas anpassen?
Habe einen Upgrade von Beta 2 auf V3.0.1 durchgeführt und bekomme folgende Fehlermeldungen:

2022-04-16 10:28:37|INFO   |CCU-Historian V3.0.1
2022-04-16 10:28:37|INFO   |(C)MDZ (info@ccu-historian.de)
2022-04-16 10:28:39|SEVERE |Exception: BUG! exception in phase 'semantic analysis' in source unit 'Config' Unsupported class file major version 61
2022-04-16 10:28:39|SEVERE |Detail: BUG! exception in phase 'semantic analysis' in source unit 'Config' Unsupported class file major version 61
	at mdz.ccuhistorian.Configuration.readFile(Configuration.groovy:138)
	at mdz.ccuhistorian.Main.start(Main.groovy:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy:77)
	at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at mdz.Exceptions.lambda$0(Exceptions.java:84)
	at mdz.Exceptions.catchToLog(Exceptions.java:74)
	at mdz.Exceptions.catchToLog(Exceptions.java:84)
	at mdz.ccuhistorian.Main.run(Main.groovy:77)
	at mdz.ccuhistorian.Main.main(Main.groovy:45)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)
	... 15 more

**Comment by jokay** [comment]
@mdzio das Docker image **3.0.1** läuft mit Java **17.0.2** problemlos.

```sh
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8)
OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)
```

```sh
2022-04-16 07:18:25|INFO   |CCU-Historian V3.0.1
2022-04-16 07:18:25|INFO   |(C)MDZ (info@ccu-historian.de)
2022-04-16 07:18:26|INFO   |Starting base services
2022-04-16 07:18:26|INFO   |Connecting to database
2022-04-16 07:18:27|INFO   |Starting database web server
2022-04-16 07:18:27|INFO   |Setting up device 1
2022-04-16 07:18:27|INFO   |Creating HM script client for http://192.168.1.90:8181/tclrega.exe
2022-04-16 07:18:27|INFO   |Configured following interfaces: t_BidCos-RF, t_HmIP-RF, t_SysVar
2022-04-16 07:18:27|INFO   |Starting interfaces
2022-04-16 07:18:27|INFO   |Starting BIN-RPC server on port 2099
2022-04-16 07:18:27|INFO   |Starting XML-RPC server on port 2098
2022-04-16 07:18:27|INFO   |Starting historian
2022-04-16 07:18:27|INFO   |Starting web server
2022-04-16 07:18:28|INFO   |Web server port: 80
```

Ich frage mich was beim Synology package anders läuft 🧐

**Comment by mdzio** [comment]
Für die zwei Synology Pakete und das CCU-Add-On wird der Groovy-Compiler V2.5 verwendet, für das allgemeine Paket, auf dem das Docker-Image basiert, der Compiler V3.0.
Am besten werde ich die Synology-Pakete dann auch mit dem Compiler V3.0 bauen.

**Comment by DidiTheE** [comment]
Vielen Dank, diese Version läuft jetzt einwandfrei auf meinem Synology DSM 7.
Auch die Performance ist massiv besser als bei der bisher von mir verwendeten Beta 2 Version.
