### ISSUE TITLE
SEVERE Exception: Unsupported class file major version 61 under Synology DSM7.01

### ISSUE THREAD

**Issue by mike-bee** [mdzio/ccu-historian#340]
Since installing V3.0.0 (and V3.0.1) CCU-Historian does not startup anymore with the following log entry being issued every 30 sec.

2022-04-22 07:37:26|INFO   |CCU-Historian V3.0.1
2022-04-22 07:37:26|INFO   |(C)MDZ (info@ccu-historian.de)
2022-04-22 07:37:27|SEVERE |Exception: BUG! exception in phase 'semantic analysis' in source unit 'Config' Unsupported class file major version 61
2022-04-22 07:37:27|SEVERE |Detail: BUG! exception in phase 'semantic analysis' in source unit 'Config' Unsupported class file major version 61
        at mdz.ccuhistorian.Configuration.readFile(Configuration.groovy:138)
        at mdz.ccuhistorian.Main.start(Main.groovy:86)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy:77)
        at mdz.ccuhistorian.Main$_run_closure4.doCall(Main.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.ccuhistorian.Main.run(Main.groovy:77)
        at mdz.ccuhistorian.Main.main(Main.groovy:45)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
        at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)

My DSM version is "7.0.1-42218 Update 3" and Java version is "17.0.2+8" installed with rednoah's Java Installer 2.17.

**Comment by mdzio** [comment]
Duplikat von #339.

Die Synology-Pakete habe ich in der [V3.0.1 Release](https://github.com/mdzio/ccu-historian/releases/tag/3.0.1) angepasst. Einfach nochmal neu herunterladen und installieren. Dann sollte der Fehler behoben sein.
