### ISSUE TITLE
Recovery Tool OutOfMemoryError und BufferUnderflowException

### ISSUE THREAD

**Issue by brgrvrm** [mdzio/ccu-historian#357]
Meine ccu-historian Datenbank scheint defekt zu sein und so wollte ich versuchen mit Hilfe des Recovery Tools die Datenbank zu reparieren. Dabei bin ich nach der Anleitung hier im Wiki zur Wiederherstellung einer defekten Datenbank vorgegangen.

Setup:
- ccu-historian-3.1.1-bin
- jre-8u341-windows-i586
- Datenbank: history.mv.db 1,062,039,552 byte

Dabei ist zuerst ein OutOfMemoryError aufgetreten.

```
D:\ccu-historian-test>java -cp lib\h2-2.1.214.jar org.h2.tools.Recover -dir data -db history
Exception in thread "main" java.lang.OutOfMemoryError: Requested memory: 1008864116
        at org.h2.util.Utils.newBytes(Utils.java:176)
        at org.h2.mvstore.MVStoreTool.dump(MVStoreTool.java:239)
        at org.h2.tools.Recover.process(Recover.java:242)
        at org.h2.tools.Recover.runTool(Recover.java:136)
        at org.h2.tools.Recover.main(Recover.java:102)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.h2.util.Utils.newBytes(Utils.java:174)
        ... 4 more
```

Nach dem Versuch den Heap Speicher zu vergrößern, bin ich auf folgende BufferUnderflowException gestoßen.

```
D:\ccu-historian-test>java -Xmx1500m -cp lib\h2-2.1.214.jar org.h2.tools.Recover -dir data -db history
Exception in thread "main" java.nio.BufferUnderflowException
        at java.nio.HeapByteBuffer.get(Unknown Source)
        at java.nio.ByteBuffer.get(Unknown Source)
        at org.h2.mvstore.MVStoreTool.dump(MVStoreTool.java:240)
        at org.h2.tools.Recover.process(Recover.java:242)
        at org.h2.tools.Recover.runTool(Recover.java:136)
        at org.h2.tools.Recover.main(Recover.java:102)
```

**Comment by mdzio** [comment]
Wenn Du mir Deine Datenbank (history.mv.db) irgendwie als Download zur Verfügung stellen kannst, kann ich sie mir mal anschauen. Den Download-Link kannst Du an die E-Mail-Adresse, die beim Start des CCU-Historians angezeigt wird, schicken.

**Comment by mdzio** [comment]
Der Java-Heap muss, wie beschrieben, vergrößert werden. Dann läuft das Recover-Werkzeug durch.

Die Datenbank ist aber wohl zu stark beschädigt, sodass das Recover-Werkzeug auch nicht mehr hilft.
