### ISSUE TITLE
Historian startet laufend neu

### ISSUE THREAD

**Issue by JHammerschmid** [mdzio/ccu-historian#390]
Raspberrypi neu aufgesetzt mit:
OS: bullseye 64bit
Java: openjdk 11.0.18 2023-01-17
ccu-historian installiert
gestartet
bricht permanent mit:
2023-05-23 19:01:10|INFO   |Starting base services
2023-05-23 19:01:10|INFO   |Connecting to database
2023-05-23 19:01:10|INFO   |Starting database web server
2023-05-23 19:01:10|INFO   |Setting up device 1
2023-05-23 19:01:10|INFO   |Creating HM script client for http://192.168.60.87:8181/tclrega.exe
2023-05-23 19:01:10|INFO   |Configured following interfaces: BidCos-RF, HmIP-RF, SysVar
2023-05-23 19:01:10|INFO   |Starting interfaces
2023-05-23 19:01:10|INFO   |Starting BIN-RPC server on port 2099
2023-05-23 19:01:10|INFO   |Starting XML-RPC server on port 2098
2023-05-23 19:01:11|INFO   |Starting historian
2023-05-23 19:01:11|INFO   |Starting web server
2023-05-23 19:01:11|INFO   |Stopping interfaces
2023-05-23 19:01:11|INFO   |Stopping BIN-RPC server on port 2099
2023-05-23 19:01:11|INFO   |Stopping database
2023-05-23 19:01:11|INFO   |Stopping base services
2023-05-23 19:01:11|SEVERE |Exception: Failed to bind to 0.0.0.0/0.0.0.0:80
2023-05-23 19:01:11|SEVERE |Detail: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:80
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
und startet neu. 
versuche 
webServer.port=85
database.webPort=8085
wie es auf der 32bit Version und JAVA 8 installiert ist zu verwenden führten zu gleichem Ergebnis.

Läuft der Historian nur unter 32Bit?

**Comment by mdzio** [comment]
> Exception: Failed to bind to 0.0.0.0/0.0.0.0:80

Diese Fehlermeldung kommt in dem Fall, wenn der Netzwerk-Port 80 von anderen Prozessen auf dem Rechner des CCU-Historians bereits belegt ist. Die Konfiguration eines anderen (nicht belegten) Ports mit der Option webServer.port sollte immer Abhilfe schaffen.

> Läuft der Historian nur unter 32Bit?

Der CCU-Historian ist sowohl unter einer 32-Bit-Java-Variante als auch einer 64-Bit lauffähig, aber vorzugsweise Java-Version 8.

**Comment by JHammerschmid** [comment]
Hier meine Konfiguration:
historian läuft noch nicht.
netstat -lnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::7070                 :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
openjdk version "11.0.18" 2023-01-17
OpenJDK Runtime Environment (build 11.0.18+10-post-Debian-1deb11u1)
OpenJDK 64-Bit Server VM (build 11.0.18+10-post-Debian-1deb11u1, mixed mode)

ccu-historian gestartet:
netstat -lnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp6       0      0 :::7070                 :::*                    LISTEN
tcp6       0      0 :::8085                 :::*                    LISTEN
tcp6       0      0 :::22                   :::*                    LISTEN
tcp6       0      0 :::2099                 :::*                    LISTEN
tcp6       0      0 :::2098                 :::*                    LISTEN

Dann folgende Fehlermeldung:
 |Starting web server
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v9.Java9 (file:/opt/ccu-historian/lib/groovy-3.0.13-indy.jar) to field java.util.ArrayList.size
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v9.Java9
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2023-05-28 08:17:46|SEVERE |Exception: sleep interrupted
2023-05-28 08:17:46|SEVERE |Detail: java.lang.InterruptedException: sleep interrupted
        at mdz.hc.itf.hm.HmScriptClient.execute(HmScriptClient.groovy:345)
        at mdz.hc.itf.hm.HmScriptClient.retrieveChannels(HmScriptClient.groovy:185)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at mdz.hc.itf.hm.HmScriptClient$_retrieveDevices_closure4.doCall(HmScriptClient.groovy:229)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at mdz.hc.itf.hm.HmScriptClient.retrieveDevices(HmScriptClient.groovy:222)
        at mdz.hc.itf.hm.HmScriptClient.getModel(HmScriptClient.groovy:305)
        at mdz.hc.itf.hm.HmXmlRpcInterface.updateLogicProperties(HmXmlRpcInterface.groovy:135)
        at mdz.hc.itf.hm.HmXmlRpcInterface.updateProperties(HmXmlRpcInterface.groovy:244)
        at mdz.hc.itf.Manager$_updateProperties_closure4.doCall(Manager.groovy:121)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at mdz.hc.itf.Manager.updateProperties(Manager.groovy:118)
        at mdz.ccuhistorian.Historian.update(Historian.groovy:157)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at mdz.ccuhistorian.Historian$_updateDataPointMeta_closure4$_closure13.doCall(Historian.groovy:115)
        at mdz.ccuhistorian.Historian$_updateDataPointMeta_closure4$_closure13.doCall(Historian.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.ccuhistorian.Historian$_updateDataPointMeta_closure4.doCall(Historian.groovy:111)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at mdz.ccuhistorian.Historian.updateDataPointMeta(Historian.groovy:110)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at mdz.ccuhistorian.Historian$_run_closure3.doCall(Historian.groovy:104)
        at mdz.ccuhistorian.Historian$_run_closure3.doCall(Historian.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at mdz.Exceptions.lambda$0(Exceptions.java:84)
        at mdz.Exceptions.catchToLog(Exceptions.java:74)
        at mdz.Exceptions.catchToLog(Exceptions.java:84)
        at mdz.ccuhistorian.Historian.run(Historian.groovy:103)
Und Neustart.

An einem belegten Port kann es nicht hängen. Sieht wohl eher nach groovy aus.
Gruß Jürgen

**Comment by mdzio** [comment]
> WARNING: An illegal reflective access operation has occurred

Die Warnung ist in Ordnung. Sie erscheint immer, wenn eine Java Version größer als 8 verwendet wird. Kannst Du bitte den CCU-Historian einmal unter Java 8 starten?

Gibt es nach dem Ausschnitt noch andere Log-Meldungen. Dort sind eventuell auch noch Informationen enthalten.

**Comment by JHammerschmid** [comment]
Hab es hinbekommen.
Geht wenn man es mit sudo aufruft.
Danke für die Unterstüzung
