### ISSUE TITLE
4.0.0 auf DSM 6 startet nicht ...

### ISSUE THREAD

**Issue by roe1974** [mdzio/ccu-historian#413]
Nach dem Update startet 4.0.0 nicht ... folgender Fehgler im log:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: mdz/ccuhistorian/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)

**Comment by roe1974** [comment]
liegt vermutlich am Java JRE 1.8.0_401 ... wird jetzt min. Java 11 benötigt ?

**Comment by mdzio** [comment]
Es wird jetzt Java 11 vorausgesetzt. Die Dokumentation muss ich noch anpassen.

**Comment by roe1974** [comment]
hmmmmmm .... zuerst das alta Java package entfernen ... oder einfach das laut Wiki dazu/drüber installieren ?
lg Richard

**Comment by UweRP** [comment]
Ähm, habe unter Windows das selbe Problem.
Unter https://www.java.com wird mir immer nur das Empfohlen Version 8 Update 401 Releasedatum: 16. Januar 2024 angeboten.
Kann mir jemand bitte einen Schups in die richtige Richtung geben wo ich Java >8 downloaden kann/soll.
Danke.

**Comment by mdzio** [comment]
Am besten die ältere Java Version als erstes entfernen.

Ich habe bei Oracle auf Anhieb auch keine andere Java-Version außer 8 gefunden. Ich selber verwende und empfehle aber auch eine andere Java-Variante von der Nicht-Profit-Organisation Eclipse: [Eclipse Temurin](https://adoptium.net/de/temurin/releases/)

**Comment by roe1974** [comment]
Super, java auf der NAS auf Eclipse Temurin ausgetauscht, jetzt läuft es ...DANKE !
(Musste nur die Fonts nach installieren) ;-)

**Comment by mdzio** [comment]
Dokumentation wurde ebenfalls angepasst.
